n = input()
a = input()
lis = a.spilt()
newlis=list(map(int,lis)
m = int(input())
b = int(input())
lis = b.split()
myset1=set(a)
myset2=set(b)
d = a.union(b)
e = a.intersection(b)
sd = d.differnce(e)
print(sd)
